name: hlavo
channels:
  - conda-forge
dependencies:
  - python=3.11

  # MODFLOW
  - modflow6

  # Heavy scientific stack (compiled)
  - numpy
  - scipy
  - matplotlib

  # Data / parallel
  - xarray
  - dask
  - distributed
  - zarr

  # IO / ingress
  - pyyaml
  - attrs
  - requests
  - cfgrib
  - eccodes   # makes cfgrib happier / more explicit

  # MODFLOW ecosystem
  - flopy

  # Small pure-python (fine in conda; keeps pip layer smaller)
  - filterpy
  - modflow-devtools

  # Allow pip installs (for git deps + ParFlow python tooling)
  - pip
  - pip:
      # ParFlow Python tooling (does NOT install ParFlow solver binary)
      - "pftools[all]"

      # Your git dependency
      - "zarr_fuse @ git+https://github.com/GeoMop/zarr_fuse.git@main"
