#!/usr/bin/env bash
set -xeuo pipefail

SCRIPT_ROOT="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

while [[ "${1:-}" == -* ]]; do
  case "$1" in
    -c)
      HLAVO_MODE="conda"
      shift
      ;;
    -t)
      tty_arg="-it"
      shift
      ;;
    *)
      break
      ;;
  esac
done

[[ $# -ge 1 ]] || { usage; exit 1; }
subcmd="$1"
shift || true

if [[ "$subcmd" == "codex" ]]; then
    HLAVO_MODE="codex"
fi

source "$SCRIPT_ROOT/hlavo_common.sh"

usage() {
  cat <<'EOF'
Usage:

  ./hlavo [-c] run <command> [args...]  

EOF
}


case "$subcmd" in
  shell)
    run_cmd "${SHELL:-bash}" -i
    ;;
  codex)
    #run_cmd bash -c "echo \$PATH"
    #run_cmd pwd
    #run_cmd python3 -c "import filterpy"
    #run_cmd python3 -c "import sys; print(sys.executable)"
    run_cmd codex "$@"
    ;;
  run)
    run_cmd "$@"
    ;;
  *)
    usage
    die "Unknown subcommand: $subcmd"
    ;;
esac
