#!/usr/bin/env python3

"""
Author: Jan Březina

This code was generated by ChatGPT and reviewed to contain main pieces of the main communication structure between the single 3D model and 
many 1D surface models. 

1. It must be tested and splitted into 1D and 3D part. 
The setup should be implemented within deep_model directory. 

2. Proper data must be passed through the queues:
From deep model to 1D models:
- end time of the next time interval
- timestep to use
- sucction pressure at the bottom of the 1D model (and top of the 3D model)
From 1D models to the deep model:
- time series, velocity at the bottom

The times should be passed as the np.datetime64[ms] objects in order to 
keep relation to the date time series of the measurements.

"""
import os
import sys
import argparse
from pathlib import Path
import numpy as np
from dask.distributed import Client, LocalCluster, get_client, Queue
from hlavo.composed.model_1d import Model1D
from hlavo.composed.model_3d import Model3D

###
# Process paths
###

def relative_to_absolute_paths(config_dict, base_dir: Path):
    if isinstance(config_dict, dict):
        for k, v in config_dict.items():
            if isinstance(v, str) and k.endswith(("_file", "_path", "_dir")):
                p = Path(v)
                if not p.is_absolute():
                    config_dict[k] = (base_dir / p).resolve()
            else:
                relative_to_absolute_paths(v, base_dir)

    elif isinstance(config_dict, list):
        for i, v in enumerate(config_dict):
            if isinstance(v, str):
                # optional: only resolve if needed
                p = Path(v)
                if not p.is_absolute():
                    config_dict[i] = (base_dir / p).resolve()
            else:
                relative_to_absolute_paths(v, base_dir)

    return config_dict




def model1d_worker_entry(idx, start_datetime, end_datetime, queue_name_in, queue_name_out, work_dir, model_kalman_config_dict, seed=123):
    """
    Entry function running on a Dask worker.
    """
    model = Model1D(site_id=idx, initial_state=0.0, work_dir=work_dir, model_kalman_config_dict=model_kalman_config_dict, seed=seed)
    return model.run_loop(start_datetime, end_datetime, queue_name_in, queue_name_out)


# ---------------------------------------------------------------------------
# Setup function
# ---------------------------------------------------------------------------

def setup_models(work_dir, config_dir, start_datetime, end_datetime, deep_model_config):
    client = get_client()

    queue_names_3d_to_1d = []
    futures_1d = []

    queue_name_1d_to_3d = "q-1d-to-3d"
    Queue(queue_name_1d_to_3d, client=client)  # ensure creation

    for i, model_1d_config in enumerate(deep_model_config["1d_models"]):
        model_1d_config_path = config_dir / Path(model_1d_config)
        model_kalman_config_dict = load_config(model_1d_config_path)

        model_kalman_config_dict = relative_to_absolute_paths(model_kalman_config_dict, config_dir)

        model_work_dir = os.path.join(work_dir, "model_1d_{}".format(i+1))
        print("model_work_dir ", model_work_dir)
        os.makedirs(model_work_dir, exist_ok=True)

        q_name_3d_to_1d = f"q-3d-to-1d-{i+1}"
        Queue(q_name_3d_to_1d, client=client)  # ensure creation

        queue_names_3d_to_1d.append(q_name_3d_to_1d)

        fut = client.submit(
            model1d_worker_entry,
            i+1,
            start_datetime, end_datetime,
            q_name_3d_to_1d,
            queue_name_1d_to_3d, model_work_dir, model_kalman_config_dict, seed=deep_model_config["seed"],
            pure=False,
        )
        futures_1d.append(fut)
        print(f"[SETUP] Submitted Model1D idx={i}")


    model_3d = Model3D(n_1d=i+1)
    final_state_3d = model_3d.run_loop(
        start_datetime, end_datetime,
        queue_names_out_to_1d=queue_names_3d_to_1d,
        queue_name_in_from_1d=queue_name_1d_to_3d,
    )

    print("\n[SETUP] Waiting for all 1D models to finish...")
    results_1d = [f.result() for f in futures_1d]
    print("[SETUP] 1D model results:", results_1d)

    return final_state_3d


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def load_config(config_path):
    import yaml
    with config_path.open("r") as f:
        config_dict = yaml.safe_load(f)
    return config_dict


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('work_dir', help='Path to work dir')
    parser.add_argument('config_file', help='Path to configuration file')

    args = parser.parse_args(sys.argv[1:])

    work_dir = Path(args.work_dir)
    composed_config_path = Path(args.config_file).resolve()
    config_dir = composed_config_path.parent

    composed_config = load_config(composed_config_path)

    cluster = LocalCluster(n_workers=4, threads_per_worker=1)
    client = Client(cluster)

    start_datetime = np.datetime64(composed_config["start_datetime"])
    end_datetime = np.datetime64(composed_config["end_datetime"])

    print("start date time ", start_datetime)
    print("end date time ", end_datetime)

    if end_datetime <= start_datetime:
        raise ValueError("end-datetime must be after start-datetime")

    final_state = setup_models(work_dir, config_dir, start_datetime, end_datetime, composed_config)
    print("\n[MAIN] Final 3D state:", final_state)

    client.close()
    cluster.close()

