seed: 123456
model_config:
  model_class_name: "ToyProblem"
  init_pressure: [-10, -100] #[-0.1, -4]   # bottom, top ; [temporary solution]
  static_params: 
    ComputationalGrid:
      "Lower.Z": -500
      "DZ": 10 #0.2
      "NZ": 50  #, 0] # Number of grid cells in z-direction
  params:
      vG_K_s: "Geom.domain.Perm.Value"
      vG_n:  ["Geom.domain.Saturation.N", "Geom.domain.RelPerm.N"]
      vG_Th_s: "Geom.domain.Saturation.SSat"
      vG_Th_r: "Geom.domain.Saturation.SRes"
      vG_alpha: ["Geom.domain.Saturation.Alpha", "Geom.domain.RelPerm.Alpha"]
  #    "Geom.domain":
  #      :
  #      "Saturation.N": [3.7, 0.1]
  evapotranspiration_params:
    names:
      - "n"
      - "T"
      - "u2"
      - "Tmax"
      - "Tmin"
      - "RHmax"
      - "RHmin"
      - "month"
    values:
      - 14
      - 20
      - 10
      - 27
      - 12
      - 0.55
      - 0.35
      - 6
measurements_config:
  model_time_step: 0.025 #2.5e-2 
  model_n_time_steps_per_iter: 1200 #40
  rain_periods: 
     - [2, 0]
     - [72, -0.01667]
     - [14, 0]

kalman_config:
  model_time_step: 2.5e-2 
  #model_n_time_steps_per_iter: 40
  state_params:
      pressure_field:
        mean_linear:
          top: -1
          bottom: -500  # top, bottom
        cov_exponential:
          std: 2.0
        Q: 0.00005
        # ref: TODO: make ref accept mean clases
        # correlation_length: 0.5
      vG_K_s:
        ref: 0.0737
      #  #mean_std: [12.833, 0.01]
        mean_std: [0.0737, 0.001 ]
        Q: 0.00000001
        #transform: lognormal            # transform to normal distribution
        #conf_interval: [0.0001, 0.01]   # implicit 0.95 confidence interval
      vG_n:
        ref: 1.89
        mean_std: [1.89, 0.01]
        Q: 0.00000001
        #transform: lognormal            # transform to normal distribution
        #conf_interval: [0.0001, 0.01]   # implicit 0.95 confidence interval
      #Th_s:
        # transform: none
        #
      #  conf_interval: [0.35, 0.41, 0.9]  # explicit 0.9 confidence interval
  train_measurements:
      saturation:
        z_pos: [10, 20, 40, 60, 100] #[-0.5, -2.5]
        noise_level: 0.1
        noise_distr_type: uniform
      #pressure:
      #  z_pos: [0.75]
      #  noise_level: 0.1
      #  noise_distr_type: uniform
      #velocity:
      #  z_pos: [0.75]
      #  noise_level: 0.1
      #  noise_distr_type: uniform
  test_measurements:
      saturation:
        z_pos: [50, 80, 200, 400]
        noise_level: 0.1
        noise_distr_type: uniform
      velocity:
        z_pos: [100, 200, 500]
        noise_level: 0.1
        noise_distr_type: uniform
      #pressure:
      #  z_pos: [1.6, 3.0]
      #  noise_level: 0.1
      #  noise_distr_type: uniform


  #measurements_data_name: "saturation"  # Possible values: "saturation" or "pressure"
  #mes_locations_train: 
  #  - 0.5
  #  - 1.4
    #- 2.5
    #- 3.5
  #mes_locations_test: 
  #  - 0.2
  #  - 0.8
  #  - 1.6
  #  - 3.0
  #measurements_noise_level: 0.1
  noise_distr_type: uniform #gaussian
  # model_params_noise_level: 0.1
  pressure_saturation_data_noise_level: 0.3   # init state noise
  #pressure_saturation_data_std: 3.2
  Q_var: 5.0e-5
  Q_model_params_var: 1e-8
  sigma_points_params: {"alpha": 0.01, "beta": 2, "kappa": 1}
postprocess:
  show: True

