name: Ingress server - push main
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-deploy:
    uses: GeoMop/zarr_fuse/.github/workflows/ingress-server-reusable-workflow.yaml@main
    with:
      deploy: true
      tag: generate
      namespace: hlavo-ingress-server
      release-name: hlavo-ingress-server
      s3-store-url: s3://hlavo-release/rancher-meteo.zarr
      configuration-dir-path: hlavo/ingress/scrapper
      docker-repository: jbrezmorf/hlavo-ingress-server
      docker-registry: docker.io
      zarr-fuse-ref: main
      extra-helm-args: >-
        --set image.name="jbrezmorf/hlavo-ingress-server"
    secrets: inherit
